/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.13.2.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class ApiBase {
    authToken = '';
    protected constructor() {
    }
    
    setAuthToken(token: string) {
        this.authToken = token;
    }
  
    protected transformOptions(options: RequestInit): Promise<any> {
        if(this.authToken)
            options.headers = {
                ...options.headers,
                "Authorization": "Bearer "+this.authToken
            }
        return Promise.resolve(options);
    }
  }
  
  export class AccountsClient extends ApiBase {
      private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
      private baseUrl: string;
      protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
  
      constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
          super();
          this.http = http ? http : <any>window;
          this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
      }
  
      registerDonor(command: RegisterDonorCommand): Promise<DonorDto> {
          let url_ = this.baseUrl + "/api/Accounts/SignUp";
          url_ = url_.replace(/[?&]$/, "");
  
          const content_ = JSON.stringify(command);
  
          let options_ = <RequestInit>{
              body: content_,
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processRegisterDonor(_response);
          });
      }
  
      protected processRegisterDonor(response: Response): Promise<DonorDto> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              result200 = DonorDto.fromJS(resultData200);
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<DonorDto>(<any>null);
      }
  }
  
  export class AuthClient extends ApiBase {
      private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
      private baseUrl: string;
      protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
  
      constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
          super();
          this.http = http ? http : <any>window;
          this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
      }
  
      signIn(request: AuthenticateRequest): Promise<AuthenticationResult> {
          let url_ = this.baseUrl + "/api/Auth";
          url_ = url_.replace(/[?&]$/, "");
  
          const content_ = JSON.stringify(request);
  
          let options_ = <RequestInit>{
              body: content_,
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processSignIn(_response);
          });
      }
  
      protected processSignIn(response: Response): Promise<AuthenticationResult> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              result200 = AuthenticationResult.fromJS(resultData200);
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<AuthenticationResult>(<any>null);
      }
  
      refreshToken(request: RefreshTokenRequest): Promise<AuthenticationResult> {
          let url_ = this.baseUrl + "/api/Auth/Refresh";
          url_ = url_.replace(/[?&]$/, "");
  
          const content_ = JSON.stringify(request);
  
          let options_ = <RequestInit>{
              body: content_,
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processRefreshToken(_response);
          });
      }
  
      protected processRefreshToken(response: Response): Promise<AuthenticationResult> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              result200 = AuthenticationResult.fromJS(resultData200);
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<AuthenticationResult>(<any>null);
      }
  
      revokeRefreshToken(request: RevokeRefreshTokenRequest): Promise<FileResponse> {
          let url_ = this.baseUrl + "/api/Auth/Revoke";
          url_ = url_.replace(/[?&]$/, "");
  
          const content_ = JSON.stringify(request);
  
          let options_ = <RequestInit>{
              body: content_,
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
                  "Accept": "application/octet-stream"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processRevokeRefreshToken(_response);
          });
      }
  
      protected processRevokeRefreshToken(response: Response): Promise<FileResponse> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200 || status === 206) {
              const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
              const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
              const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
              return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<FileResponse>(<any>null);
      }
  }
  
  export class DictionariesClient extends ApiBase {
      private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
      private baseUrl: string;
      protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
  
      constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
          super();
          this.http = http ? http : <any>window;
          this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
      }
  
      getBloodTypes(): Promise<BloodTypeDto[]> {
          let url_ = this.baseUrl + "/api/Dictionaries/BloodTypes";
          url_ = url_.replace(/[?&]$/, "");
  
          let options_ = <RequestInit>{
              method: "GET",
              headers: {
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processGetBloodTypes(_response);
          });
      }
  
      protected processGetBloodTypes(response: Response): Promise<BloodTypeDto[]> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              if (Array.isArray(resultData200)) {
                  result200 = [] as any;
                  for (let item of resultData200)
                      result200!.push(BloodTypeDto.fromJS(item));
              }
              else {
                  result200 = <any>null;
              }
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<BloodTypeDto[]>(<any>null);
      }
  }
  
  export class DonorsClient extends ApiBase {
      private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
      private baseUrl: string;
      protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
  
      constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
          super();
          this.http = http ? http : <any>window;
          this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
      }
  
      getCurrentDonorInfo(): Promise<DonorDto> {
          let url_ = this.baseUrl + "/api/Donors/Info";
          url_ = url_.replace(/[?&]$/, "");
  
          let options_ = <RequestInit>{
              method: "GET",
              headers: {
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processGetCurrentDonorInfo(_response);
          });
      }
  
      protected processGetCurrentDonorInfo(response: Response): Promise<DonorDto> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              result200 = DonorDto.fromJS(resultData200);
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<DonorDto>(<any>null);
      }
  
      getDonations(): Promise<DonationGroupDto[]> {
          let url_ = this.baseUrl + "/api/Donors/Donations";
          url_ = url_.replace(/[?&]$/, "");
  
          let options_ = <RequestInit>{
              method: "GET",
              headers: {
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processGetDonations(_response);
          });
      }
  
      protected processGetDonations(response: Response): Promise<DonationGroupDto[]> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              if (Array.isArray(resultData200)) {
                  result200 = [] as any;
                  for (let item of resultData200)
                      result200!.push(DonationGroupDto.fromJS(item));
              }
              else {
                  result200 = <any>null;
              }
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<DonationGroupDto[]>(<any>null);
      }
  
      addDonation(donations: DonationDto[]): Promise<DonationDto[]> {
          let url_ = this.baseUrl + "/api/Donors/Donations";
          url_ = url_.replace(/[?&]$/, "");
  
          const content_ = JSON.stringify(donations);
  
          let options_ = <RequestInit>{
              body: content_,
              method: "PUT",
              headers: {
                  "Content-Type": "application/json",
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processAddDonation(_response);
          });
      }
  
      protected processAddDonation(response: Response): Promise<DonationDto[]> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              if (Array.isArray(resultData200)) {
                  result200 = [] as any;
                  for (let item of resultData200)
                      result200!.push(DonationDto.fromJS(item));
              }
              else {
                  result200 = <any>null;
              }
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<DonationDto[]>(<any>null);
      }
  
      getDonationSummary(donationType: string | null | undefined): Promise<DonationSummaryDto> {
          let url_ = this.baseUrl + "/api/Donors/Summary?";
          if (donationType !== undefined && donationType !== null)
              url_ += "donationType=" + encodeURIComponent("" + donationType) + "&";
          url_ = url_.replace(/[?&]$/, "");
  
          let options_ = <RequestInit>{
              method: "GET",
              headers: {
                  "Accept": "application/json"
              }
          };
  
          return this.transformOptions(options_).then(transformedOptions_ => {
              return this.http.fetch(url_, transformedOptions_);
          }).then((_response: Response) => {
              return this.processGetDonationSummary(_response);
          });
      }
  
      protected processGetDonationSummary(response: Response): Promise<DonationSummaryDto> {
          const status = response.status;
          let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
          if (status === 200) {
              return response.text().then((_responseText) => {
              let result200: any = null;
              let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
              result200 = DonationSummaryDto.fromJS(resultData200);
              return result200;
              });
          } else if (status !== 200 && status !== 204) {
              return response.text().then((_responseText) => {
              return throwException("An unexpected server error occurred.", status, _responseText, _headers);
              });
          }
          return Promise.resolve<DonationSummaryDto>(<any>null);
      }
  }
  
  export class DonorDto implements IDonorDto {
      id?: string;
      firstName?: string | undefined;
      lastName?: string | undefined;
      birthDay?: Date;
      gender?: GenderType;
      bloodType?: BloodTypeDto | undefined;
  
      constructor(data?: IDonorDto) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
              this.bloodType = data.bloodType && !(<any>data.bloodType).toJSON ? new BloodTypeDto(data.bloodType) : <BloodTypeDto>this.bloodType; 
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.id = _data["id"];
              this.firstName = _data["firstName"];
              this.lastName = _data["lastName"];
              this.birthDay = _data["birthDay"] ? new Date(_data["birthDay"].toString()) : <any>undefined;
              this.gender = _data["gender"];
              this.bloodType = _data["bloodType"] ? BloodTypeDto.fromJS(_data["bloodType"]) : <any>undefined;
          }
      }
  
      static fromJS(data: any): DonorDto {
          data = typeof data === 'object' ? data : {};
          let result = new DonorDto();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["id"] = this.id;
          data["firstName"] = this.firstName;
          data["lastName"] = this.lastName;
          data["birthDay"] = this.birthDay ? this.birthDay.toISOString() : <any>undefined;
          data["gender"] = this.gender;
          data["bloodType"] = this.bloodType ? this.bloodType.toJSON() : <any>undefined;
          return data; 
      }
  }
  
  export interface IDonorDto {
      id?: string;
      firstName?: string | undefined;
      lastName?: string | undefined;
      birthDay?: Date;
      gender?: GenderType;
      bloodType?: IBloodTypeDto | undefined;
  }
  
  export enum GenderType {
      Male = 1,
      Female = 2,
  }
  
  export class BloodTypeDto implements IBloodTypeDto {
      label?: string | undefined;
      symbol?: string | undefined;
  
      constructor(data?: IBloodTypeDto) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.label = _data["label"];
              this.symbol = _data["symbol"];
          }
      }
  
      static fromJS(data: any): BloodTypeDto {
          data = typeof data === 'object' ? data : {};
          let result = new BloodTypeDto();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["label"] = this.label;
          data["symbol"] = this.symbol;
          return data; 
      }
  }
  
  export interface IBloodTypeDto {
      label?: string | undefined;
      symbol?: string | undefined;
  }
  
  export class RegisterDonorCommand implements IRegisterDonorCommand {
      userName?: string | undefined;
      email?: string | undefined;
      password?: string | undefined;
      confirmPassword?: string | undefined;
      firstName?: string | undefined;
      lastName?: string | undefined;
      gender?: GenderType;
      bloodTypeLabel?: string | undefined;
      birthDay?: Date;
  
      constructor(data?: IRegisterDonorCommand) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.userName = _data["userName"];
              this.email = _data["email"];
              this.password = _data["password"];
              this.confirmPassword = _data["confirmPassword"];
              this.firstName = _data["firstName"];
              this.lastName = _data["lastName"];
              this.gender = _data["gender"];
              this.bloodTypeLabel = _data["bloodTypeLabel"];
              this.birthDay = _data["birthDay"] ? new Date(_data["birthDay"].toString()) : <any>undefined;
          }
      }
  
      static fromJS(data: any): RegisterDonorCommand {
          data = typeof data === 'object' ? data : {};
          let result = new RegisterDonorCommand();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["userName"] = this.userName;
          data["email"] = this.email;
          data["password"] = this.password;
          data["confirmPassword"] = this.confirmPassword;
          data["firstName"] = this.firstName;
          data["lastName"] = this.lastName;
          data["gender"] = this.gender;
          data["bloodTypeLabel"] = this.bloodTypeLabel;
          data["birthDay"] = this.birthDay ? this.birthDay.toISOString() : <any>undefined;
          return data; 
      }
  }
  
  export interface IRegisterDonorCommand {
      userName?: string | undefined;
      email?: string | undefined;
      password?: string | undefined;
      confirmPassword?: string | undefined;
      firstName?: string | undefined;
      lastName?: string | undefined;
      gender?: GenderType;
      bloodTypeLabel?: string | undefined;
      birthDay?: Date;
  }
  
  export class AuthenticationResult implements IAuthenticationResult {
      success?: boolean;
      message?: string | undefined;
      accessToken?: JwtToken | undefined;
      refreshToken?: JwtToken | undefined;
  
      constructor(data?: IAuthenticationResult) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
              this.accessToken = data.accessToken && !(<any>data.accessToken).toJSON ? new JwtToken(data.accessToken) : <JwtToken>this.accessToken; 
              this.refreshToken = data.refreshToken && !(<any>data.refreshToken).toJSON ? new JwtToken(data.refreshToken) : <JwtToken>this.refreshToken; 
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.success = _data["success"];
              this.message = _data["message"];
              this.accessToken = _data["accessToken"] ? JwtToken.fromJS(_data["accessToken"]) : <any>undefined;
              this.refreshToken = _data["refreshToken"] ? JwtToken.fromJS(_data["refreshToken"]) : <any>undefined;
          }
      }
  
      static fromJS(data: any): AuthenticationResult {
          data = typeof data === 'object' ? data : {};
          let result = new AuthenticationResult();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["success"] = this.success;
          data["message"] = this.message;
          data["accessToken"] = this.accessToken ? this.accessToken.toJSON() : <any>undefined;
          data["refreshToken"] = this.refreshToken ? this.refreshToken.toJSON() : <any>undefined;
          return data; 
      }
  }
  
  export interface IAuthenticationResult {
      success?: boolean;
      message?: string | undefined;
      accessToken?: IJwtToken | undefined;
      refreshToken?: IJwtToken | undefined;
  }
  
  export class JwtToken implements IJwtToken {
      token?: string | undefined;
      expireAt?: Date;
  
      constructor(data?: IJwtToken) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.token = _data["token"];
              this.expireAt = _data["expireAt"] ? new Date(_data["expireAt"].toString()) : <any>undefined;
          }
      }
  
      static fromJS(data: any): JwtToken {
          data = typeof data === 'object' ? data : {};
          let result = new JwtToken();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["token"] = this.token;
          data["expireAt"] = this.expireAt ? this.expireAt.toISOString() : <any>undefined;
          return data; 
      }
  }
  
  export interface IJwtToken {
      token?: string | undefined;
      expireAt?: Date;
  }
  
  export class AuthenticateRequest implements IAuthenticateRequest {
      usernameOrEmail?: string | undefined;
      password?: string | undefined;
  
      constructor(data?: IAuthenticateRequest) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.usernameOrEmail = _data["usernameOrEmail"];
              this.password = _data["password"];
          }
      }
  
      static fromJS(data: any): AuthenticateRequest {
          data = typeof data === 'object' ? data : {};
          let result = new AuthenticateRequest();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["usernameOrEmail"] = this.usernameOrEmail;
          data["password"] = this.password;
          return data; 
      }
  }
  
  export interface IAuthenticateRequest {
      usernameOrEmail?: string | undefined;
      password?: string | undefined;
  }
  
  export class RefreshTokenRequest implements IRefreshTokenRequest {
      refreshToken?: string | undefined;
  
      constructor(data?: IRefreshTokenRequest) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.refreshToken = _data["refreshToken"];
          }
      }
  
      static fromJS(data: any): RefreshTokenRequest {
          data = typeof data === 'object' ? data : {};
          let result = new RefreshTokenRequest();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["refreshToken"] = this.refreshToken;
          return data; 
      }
  }
  
  export interface IRefreshTokenRequest {
      refreshToken?: string | undefined;
  }
  
  export class RevokeRefreshTokenRequest implements IRevokeRefreshTokenRequest {
      refreshToken?: string | undefined;
  
      constructor(data?: IRevokeRefreshTokenRequest) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.refreshToken = _data["refreshToken"];
          }
      }
  
      static fromJS(data: any): RevokeRefreshTokenRequest {
          data = typeof data === 'object' ? data : {};
          let result = new RevokeRefreshTokenRequest();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["refreshToken"] = this.refreshToken;
          return data; 
      }
  }
  
  export interface IRevokeRefreshTokenRequest {
      refreshToken?: string | undefined;
  }
  
  export class DonationGroupDto implements IDonationGroupDto {
      key?: string | undefined;
      donations?: DonationDto[] | undefined;
  
      constructor(data?: IDonationGroupDto) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
              if (data.donations) {
                  this.donations = [];
                  for (let i = 0; i < data.donations.length; i++) {
                      let item = data.donations[i];
                      this.donations[i] = item && !(<any>item).toJSON ? new DonationDto(item) : <DonationDto>item;
                  }
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.key = _data["key"];
              if (Array.isArray(_data["donations"])) {
                  this.donations = [] as any;
                  for (let item of _data["donations"])
                      this.donations!.push(DonationDto.fromJS(item));
              }
          }
      }
  
      static fromJS(data: any): DonationGroupDto {
          data = typeof data === 'object' ? data : {};
          let result = new DonationGroupDto();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["key"] = this.key;
          if (Array.isArray(this.donations)) {
              data["donations"] = [];
              for (let item of this.donations)
                  data["donations"].push(item.toJSON());
          }
          return data; 
      }
  }
  
  export interface IDonationGroupDto {
      key?: string | undefined;
      donations?: IDonationDto[] | undefined;
  }
  
  export class DonationDto implements IDonationDto {
      date?: Date;
      location?: string | undefined;
      volume?: number;
      donationTypeLabel?: string | undefined;
  
      constructor(data?: IDonationDto) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
              this.location = _data["location"];
              this.volume = _data["volume"];
              this.donationTypeLabel = _data["donationTypeLabel"];
          }
      }
  
      static fromJS(data: any): DonationDto {
          data = typeof data === 'object' ? data : {};
          let result = new DonationDto();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["date"] = this.date ? this.date.toISOString() : <any>undefined;
          data["location"] = this.location;
          data["volume"] = this.volume;
          data["donationTypeLabel"] = this.donationTypeLabel;
          return data; 
      }
  }
  
  export interface IDonationDto {
      date?: Date;
      location?: string | undefined;
      volume?: number;
      donationTypeLabel?: string | undefined;
  }
  
  export class DonationSummaryDto implements IDonationSummaryDto {
      donationType?: string | undefined;
      count?: number;
      amount?: number;
  
      constructor(data?: IDonationSummaryDto) {
          if (data) {
              for (var property in data) {
                  if (data.hasOwnProperty(property))
                      (<any>this)[property] = (<any>data)[property];
              }
          }
      }
  
      init(_data?: any) {
          if (_data) {
              this.donationType = _data["donationType"];
              this.count = _data["count"];
              this.amount = _data["amount"];
          }
      }
  
      static fromJS(data: any): DonationSummaryDto {
          data = typeof data === 'object' ? data : {};
          let result = new DonationSummaryDto();
          result.init(data);
          return result;
      }
  
      toJSON(data?: any) {
          data = typeof data === 'object' ? data : {};
          data["donationType"] = this.donationType;
          data["count"] = this.count;
          data["amount"] = this.amount;
          return data; 
      }
  }
  
  export interface IDonationSummaryDto {
      donationType?: string | undefined;
      count?: number;
      amount?: number;
  }
  
  export interface FileResponse {
      data: Blob;
      status: number;
      fileName?: string;
      headers?: { [name: string]: any };
  }
  
  export class ApiException extends Error {
      message: string;
      status: number;
      response: string;
      headers: { [key: string]: any; };
      result: any;
  
      constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
          super();
  
          this.message = message;
          this.status = status;
          this.response = response;
          this.headers = headers;
          this.result = result;
      }
  
      protected isApiException = true;
  
      static isApiException(obj: any): obj is ApiException {
          return obj.isApiException === true;
      }
  }
  
  function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
      if (result !== null && result !== undefined)
          throw result;
      else
          throw new ApiException(message, status, response, headers, null);
  }